### ISSUE TITLE
Following a style guide and Improve method names

### ISSUE THREAD

**Issue by tacticiankerala** [geekskool/ruby-lisp-interpreter#2]
- Following a ruby style guide helps in readability of the code(especially by other rubyists). Here is a style guide you might want to follow https://github.com/bbatsov/ruby-style-guide
- Improving the method names to reveal their intentions is also important. For example, trying to remember what `check` method does can get a bit difficult.

One rule of thumb to follow is,  

> Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. Code for readability.

**Comment by adarsh-why** [comment]
Sorry for my method names. I will change to meaningful names.
Thanks for the style-guide. :+1:

**Comment by adarsh-why** [comment]
Fixed it.
